# Generated by Django 2.1.7 on 2019-04-03 16:03

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0004_trophy_trophyuserrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[account.validators.UsernameValidator()],
                                   verbose_name='ユーザーID'),
        ),
    ]
