# Generated by Django 2.1.7 on 2019-04-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0007_auto_20190404_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_accept_mail',
            field=models.BooleanField(default=True, verbose_name='メール配信の許可'),
        ),
    ]
