# Generated by Django 2.1.8 on 2019-06-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0011_auto_20190508_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contribution_point',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='貢献ポイント'),
        ),
    ]
