# Generated by Django 2.1.8 on 2019-04-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_video_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprofile',
            name='allows_anonymous_comment',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
