# Generated by Django 2.1.8 on 2019-04-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('browse', '0003_channel'),
        ('upload', '0006_videoprofile_ordered_fps'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprofile',
            name='channels',
            field=models.ManyToManyField(blank=True, null=True, to='browse.Channel', verbose_name='チャンネル'),
        ),
    ]
