# Generated by Django 2.1.8 on 2019-04-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('browse', '0008_auto_20190430_2101'),
        ('upload', '0010_videoprofile_channels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoprofile',
            name='channels',
        ),
        migrations.AddField(
            model_name='videoprofile',
            name='labels',
            field=models.ManyToManyField(blank=True, through='browse.VideoProfileLabelRelation', to='browse.Labels',
                                         verbose_name='チャンネル'),
        ),
    ]
