# Generated by Django 2.1.8 on 2019-06-15 06:44

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):
    dependencies = [
        ('upload', '0016_auto_20190612_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodata',
            name='gif',
            field=models.FileField(blank=True, null=True, upload_to=upload.models.gif_upload_to,
                                   verbose_name='gifサムネイル'),
        ),
    ]
