# Generated by Django 2.1.4 on 2019-01-04 03:27

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='本文')),
                ('slug', models.SlugField(verbose_name='スラッグ')),
                ('published', models.BooleanField(verbose_name='公開する', default=True)),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='筆者')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
