# Generated by Django 2.1.7 on 2019-03-23 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('text', markdownx.models.MarkdownxField(verbose_name='本文')),
                ('slug', models.SlugField(verbose_name='スラッグ')),
                ('is_published', models.BooleanField(default=True, verbose_name='公開する')),
                ('author',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL,
                                   verbose_name='筆者')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
