# Generated by Django 2.1.8 on 2019-04-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='featured_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='トップ表示順'),
        ),
    ]
