# Generated by Django 2.1.7 on 2019-03-18 10:10

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):
    dependencies = [
        ('pages', '0002_auto_20190104_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='text',
            field=markdownx.models.MarkdownxField(verbose_name='本文'),
        ),
    ]
