# Generated by Django 2.1.8 on 2019-04-30 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('browse', '0005_videoprofilechannelrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoprofilechannelrelation',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='browse.Channel'),
        ),
    ]
