# Generated by Django 2.1.8 on 2019-04-30 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('upload', '0009_remove_videoprofile_channels'),
        ('browse', '0006_auto_20190430_1746'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videoprofilechannelrelation',
            unique_together={('profile', 'channel')},
        ),
    ]
