# Generated by Django 2.1.8 on 2019-04-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('upload', '0010_videoprofile_channels'),
        ('browse', '0007_auto_20190430_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProfileLabelRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='videoprofilechannelrelation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='videoprofilechannelrelation',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='videoprofilechannelrelation',
            name='profile',
        ),
        migrations.RenameModel(
            old_name='Channel',
            new_name='Labels',
        ),
    ]
