# Generated by Django 2.1.8 on 2019-04-28 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('upload', '0004_auto_20190416_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=0, verbose_name='算出ポイント')),
                ('day', models.IntegerField(choices=[('24時間', 1), ('週間', 7), ('月間', 30), ('全期間', -1)], default=1,
                                            verbose_name='期間(日)')),
                ('type', models.CharField(choices=[('お気に入り順', 'favorites')], default='popular', max_length=20,
                                          verbose_name='集計タイプ')),
                ('video',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Video', verbose_name='動画')),
            ],
        ),
    ]
