# Generated by Django 2.1.8 on 2019-04-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('browse', '0002_auto_20190428_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='チャンネル名')),
                ('description', models.TextField(verbose_name='チャンネル説明')),
            ],
        ),
    ]
