# Generated by Django 2.1.8 on 2019-04-30 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('upload', '0013_auto_20190430_2117'),
        ('browse', '0009_auto_20190430_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='スラッグ')),
                ('color', models.CharField(max_length=10, verbose_name='色')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('description', models.TextField(verbose_name='説明')),
            ],
        ),
        migrations.AlterField(
            model_name='videoprofilelabelrelation',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='browse.Label'),
        ),
        migrations.DeleteModel(
            name='Labels',
        ),
    ]
