# Generated by Django 2.1.8 on 2019-04-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('browse', '0010_auto_20190430_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(
                choices=[('orange', 'orange'), ('yellow', 'yellow'), ('green', 'green'), ('turqoise', 'turqoise'),
                         ('cyan', 'cyan'), ('blue', 'blue'), ('purple', 'purple'), ('red', 'red'), ('pink', 'pink'),
                         ('grey', 'grey'), ('grey-light', 'grey-light'), ('grey-lighter', 'grey-lighter')],
                max_length=10, verbose_name='色'),
        ),
    ]
