# Generated by Django 2.1.8 on 2019-06-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('browse', '0012_auto_20190509_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='アクティブ'),
        ),
    ]
