# Generated by Django 2.1.8 on 2019-05-08 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_altwugauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('ip_joined', models.GenericIPAddressField(verbose_name='初回ログイン時のIP')),
                ('ip_latest', models.GenericIPAddressField(verbose_name='最終ログイン時のIP')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                              verbose_name='ユーザー')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
