# Generated by Django 2.1.8 on 2019-05-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0010_accesslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='ip_joined',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='初回ログイン時のIP'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='ip_latest',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='最終ログイン時のIP'),
        ),
    ]
