# Generated by Django 2.1.11 on 2019-12-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tools', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ua',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='動作環境'),
        ),
    ]
