# Generated by Django 2.1.7 on 2019-03-05 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=upload.models.default_video_slug, max_length=5)),
                ('file', models.FileField(upload_to=upload.models.video_upload_to)),
                ('fps', models.PositiveIntegerField()),
                ('duration', models.FloatField()),
                ('thumbnail', models.ImageField(upload_to=upload.models.thumbnail_upload_to)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='upload.Video')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
