# Generated by Django 2.1.7 on 2019-03-07 09:04

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.CharField(default=upload.models.default_video_slug, editable=False, max_length=5, verbose_name='動画ID'),
        ),
    ]
