# Generated by Django 2.1.7 on 2019-03-06 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='videoprofile',
            name='thumbnail',
            field=models.ImageField(upload_to=upload.models.thumbnail_upload_to, verbose_name='サムネイル'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.FloatField(verbose_name='動画時間'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to=upload.models.video_upload_to, verbose_name='動画ファイル'),
        ),
        migrations.AlterField(
            model_name='video',
            name='fps',
            field=models.PositiveIntegerField(verbose_name='FPS'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.CharField(default=upload.models.default_video_slug, max_length=5, verbose_name='動画ID'),
        ),
        migrations.AlterField(
            model_name='video',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者'),
        ),
        migrations.AlterField(
            model_name='videoprofile',
            name='description',
            field=models.TextField(max_length=200, verbose_name='動画説明'),
        ),
        migrations.AlterField(
            model_name='videoprofile',
            name='title',
            field=models.CharField(max_length=50, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='videoprofile',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='upload.Video', verbose_name='動画'),
        ),
    ]
