# Generated by Django 2.1.7 on 2019-03-12 08:52

import django.core.files.storage
from django.db import migrations, models

import upload.models
import upload.validators


class Migration(migrations.Migration):
    dependencies = [
        ('upload', '0002_auto_20190307_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedpurevideo',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(),
                                   upload_to=upload.models.temp_upload_to, validators=[
                    upload.validators.FileValidator(allowed_extensions=['mp4'], max_size=104857600),
                    upload.validators.video_file_validator], verbose_name='動画ファイル'),
        ),
    ]
