# Generated by Django 2.1.7 on 2019-03-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('upload', '0003_auto_20190312_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpurevideo',
            name='is_encoding',
            field=models.BooleanField(default=False, verbose_name='エンコード開始済み'),
        ),
        migrations.AddField(
            model_name='uploadedpurevideo',
            name='is_failed',
            field=models.BooleanField(default=False, verbose_name='エンコード失敗'),
        ),
    ]
