# Generated by Django 2.1.7 on 2019-03-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('upload', '0006_video_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoprofile',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='動画説明'),
        ),
    ]
