# Generated by Django 2.1.8 on 2019-04-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('upload', '0007_videoprofile_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoprofile',
            name='channels',
            field=models.ManyToManyField(blank=True, to='browse.Channel', verbose_name='チャンネル'),
        ),
    ]
