# Generated by Django 2.1.7 on 2019-03-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('upload', '0007_auto_20190321_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.CharField(
                choices=[('normal', '通常投稿'), ('twitter', 'ツイッターからインポート'), ('altwug', 'Altwugからインポート')],
                default='normal', max_length=20, verbose_name='動画タイプ'),
        ),
    ]
