# Generated by Django 2.1.7 on 2019-03-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('upload', '0009_auto_20190323_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='公開'),
        ),
    ]
