# Generated by Django 2.1.7 on 2019-03-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('upload', '0010_video_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='公開時間'),
        ),
    ]
