# Generated by Django 2.1.7 on 2019-03-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('upload', '0011_video_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoprofile',
            name='description',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='動画説明'),
        ),
    ]
