# Generated by Django 2.1.8 on 2019-06-11 14:00

from django.db import migrations, models
import upload.models
import upload.validators


class Migration(migrations.Migration):
    dependencies = [
        ('upload', '0014_auto_20190526_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprofile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=upload.models.profile_upload_to, validators=[
                upload.validators.FileValidator(allowed_extensions=['zip'], max_size=104857600)], verbose_name='ファイル'),
        ),
    ]
