# Generated by Django 2.1.8 on 2019-06-12 14:10

from django.db import migrations, models
import upload.models
import upload.validators


class Migration(migrations.Migration):
    dependencies = [
        ('upload', '0015_videoprofile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoprofile',
            name='file',
            field=models.FileField(blank=True, help_text='動画出力前のデータ(pclx, kwzなど)を配布したい方向け。zip形式のみ対応', null=True,
                                   upload_to=upload.models.profile_upload_to, validators=[
                    upload.validators.FileValidator(allowed_extensions=['zip'], max_size=104857600),
                    upload.validators.zip_validator], verbose_name='添付ファイル'),
        ),
    ]
