# Generated by Django 2.1.8 on 2019-06-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('upload', '0017_videodata_gif'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_pickup',
            field=models.BooleanField(default=False, verbose_name='ピックアップ'),
        ),
    ]
