# Generated by Django 2.1.7 on 2019-03-27 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, verbose_name='本文')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                           verbose_name='ユーザー')),
                ('video',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Video', verbose_name='動画')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('count', models.PositiveIntegerField(verbose_name='ポイント')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('video',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Video', verbose_name='動画')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
