# Generated by Django 2.1.7 on 2019-03-19 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('upload', '0006_video_views_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ajax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='ポイント')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                           verbose_name='ユーザー')),
                ('video',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Video', verbose_name='動画')),
            ],
        ),
    ]
