# Generated by Django 2.1.7 on 2019-03-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ajax', '0002_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
    ]
