# Generated by Django 2.1.8 on 2019-06-08 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('name', models.CharField(default='名無し', max_length=20, verbose_name='名前')),
                ('text', models.TextField(max_length=140, verbose_name='本文')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
